Issue #sb-forms : allow ecm fix
Sunbird-Ed/SunbirdEd-forms pull request #138
Opened 2021-12-30 13:42 UTC by pradeepkumarcm96

###

2021-12-30 14:37 UTC, venkateshwarans commented on projects/common-form-elements/src/lib/keywords/keywords.component.ts
> +console.log(this.formControlRef.isVisible);
remove the console.log

2021-12-30 14:38 UTC, venkateshwarans commented on projects/common-form-elements/src/lib/keywords/keywords.component.ts
> +     }
are we making use of `this.latestParentValue` value anywhere? if not please remove this entire if condition for now and add the `this.contextValueChangesSubscription` to line.no 59.

2021-12-30 14:41 UTC, venkateshwarans requested changes
see comments

2021-12-31 05:32 UTC, venkateshwarans commented on projects/common-form-elements/src/lib/keywords/keywords.component.ts
> +    this.options$.subscribe(
add `contextValueChangesSubscription` here

2021-12-31 06:30 UTC, venkateshwarans approved these changes

2021-12-31 06:32 UTC, pallakartheekreddy approved these changes

2021-12-31 06:32 UTC, merged